# SANDBOX

In [154]:
import collections
import json
import pandas as pd

from pprint import pprint
from pyairtable import Table

In [155]:
with open('credentials.json', 'r') as fp:
    credentials = json.load(fp)

In [200]:
base_id = credentials["base_id"]
api_key = credentials["api_key"]

In [201]:
def get_df_from_airtable(table_name="JOURNAL", zero_fill=5):
    table = Table(api_key, base_id, table_name)
    rows = collections.defaultdict(dict)
    for i, dic in enumerate(table.all()):
        row_key = f"row_{str(i).zfill(zero_fill)}"
        rows[row_key] = dic["fields"]
        rows[row_key]["id"] = dic["id"]
        rows[row_key]["created_at"] = dic["createdTime"]
    rows_json = json.dumps(rows)
    df = pd.read_json(rows_json, orient='index')
    return df

In [202]:
df_journal = get_df_from_airtable("JOURNAL")
df_journal.head()

,Date,Exercise,Order,Rest,Duration,Series,Reps,Weight (kg),Notes,Tool (from Exercise),id,created_at
row_00000,2022-07-18,[recSI1YSnPbapYxxU],3,2700,0,3,12,15.0,Biset with squat\n,[Sandbag],rec8PfbGuChgCHBy4,2022-07-18 22:24:44+00:00
row_00001,2022-07-18,[recME1acBxM1b6AV4],5,2700,0,3,12,6.0,Biset with leg curl\n2x6kg\n,[Kettlebells (2)],rec8gGo2vSU8elGpn,2022-07-18 22:27:06+00:00
row_00002,2022-07-18,[recs0jFtTmQfGyPu2],7,2700,0,3,12,8.0,Biset with leg extension\n,[Kettlebells (2)],rec9x7ZWD4sRRvqe3,2022-07-18 23:35:30+00:00
row_00003,2022-07-18,[recU2wxVvW0ABd399],16,1800,0,3,12,NaN,Not much at ease with posture yet\n,[Battle ropes (2)],recBIG2Ixng4OkPJ4,2022-07-18 23:05:14+00:00
row_00004,2022-07-18,[recPefwnEXqv1SHtY],18,1800,0,3,12,NaN,Not much at ease with posture yet\n,[Battle ropes (2)],recGFQzOuIVmKPHx0,2022-07-18 23:05:41+00:00

In [203]:
df_journal["Exercise"].values[0]

['recSI1YSnPbapYxxU']

In [204]:
ids = df_exercises["id"]
#ids = [f"[{i}]" for i in ids]
exercises = df_exercises["Exercise"]
exercise_ids = dict(zip(ids, exercises))

In [205]:
exercise_ids

{'recG3D1iWER7HYCI1': 'Deadhang pull up',
 'recME1acBxM1b6AV4': 'Lateral raise',
 'recPefwnEXqv1SHtY': 'Battle ropes - snake waves',
 'recQdtCK6WKDORiIK': 'Arnold press',
 'recSI1YSnPbapYxxU': 'Front raise',
 'recU2wxVvW0ABd399': 'Battle ropes - unilateral waves',
 'recVIXAEGyS2ntyqR': 'Battle ropes - inside waves',
 'recVeC7yLuQyjmEAG': 'Leg extension',
 'recYFxmpeucUwM55h': 'Battle ropes - bilateral waves',
 'recdonfegjF3WS9fX': '3K',
 'recghWflrZ710Bu74': 'Leg curl',
 'reciS6KzZpvG1SEIN': 'Squats',
 'recqGRt2xovgm6hEH': 'Roman chair knee raise',
 'recs0jFtTmQfGyPu2': 'Upright rows',
 'recygFoz49Zw8Zyxy': 'Battle ropes - slamming waves'}

In [206]:
df_journal["Exercise"]

row_00000    [recSI1YSnPbapYxxU]
row_00001    [recME1acBxM1b6AV4]
row_00002    [recs0jFtTmQfGyPu2]
row_00003    [recU2wxVvW0ABd399]
row_00004    [recPefwnEXqv1SHtY]
row_00005    [recYFxmpeucUwM55h]
row_00006    [recdonfegjF3WS9fX]
row_00007    [recqGRt2xovgm6hEH]
row_00008    [recghWflrZ710Bu74]
row_00009    [recVeC7yLuQyjmEAG]
row_00010    [recG3D1iWER7HYCI1]
row_00011    [recygFoz49Zw8Zyxy]
row_00012    [recVIXAEGyS2ntyqR]
row_00013    [reciS6KzZpvG1SEIN]
row_00014    [recqGRt2xovgm6hEH]
row_00015    [recG3D1iWER7HYCI1]
row_00016    [recQdtCK6WKDORiIK]
row_00017    [recG3D1iWER7HYCI1]
Name: Exercise, dtype: object

In [207]:
df_journal["Exercise"] = df_journal["Exercise"]#.str.replace("[", "",regex=True)
df_journal["Exercise"]

row_00000    [recSI1YSnPbapYxxU]
row_00001    [recME1acBxM1b6AV4]
row_00002    [recs0jFtTmQfGyPu2]
row_00003    [recU2wxVvW0ABd399]
row_00004    [recPefwnEXqv1SHtY]
row_00005    [recYFxmpeucUwM55h]
row_00006    [recdonfegjF3WS9fX]
row_00007    [recqGRt2xovgm6hEH]
row_00008    [recghWflrZ710Bu74]
row_00009    [recVeC7yLuQyjmEAG]
row_00010    [recG3D1iWER7HYCI1]
row_00011    [recygFoz49Zw8Zyxy]
row_00012    [recVIXAEGyS2ntyqR]
row_00013    [reciS6KzZpvG1SEIN]
row_00014    [recqGRt2xovgm6hEH]
row_00015    [recG3D1iWER7HYCI1]
row_00016    [recQdtCK6WKDORiIK]
row_00017    [recG3D1iWER7HYCI1]
Name: Exercise, dtype: object

In [211]:
df_journal["Exercise"] = df_journal["Exercise"].apply(lambda c: [exercise_ids.get(v) for v in c])
df_journal["Exercise"] = df_journal["Exercise"].apply("".join)

In [212]:
df_journal

,Date,Exercise,Order,Rest,Duration,Series,Reps,Weight (kg),Notes,Tool (from Exercise),id,created_at
row_00000,2022-07-18,Front raise,3,2700,0,3,12,15.0,Biset with squat\n,[Sandbag],rec8PfbGuChgCHBy4,2022-07-18 22:24:44+00:00
row_00001,2022-07-18,Lateral raise,5,2700,0,3,12,6.0,Biset with leg curl\n2x6kg\n,[Kettlebells (2)],rec8gGo2vSU8elGpn,2022-07-18 22:27:06+00:00
row_00002,2022-07-18,Upright rows,7,2700,0,3,12,8.0,Biset with leg extension\n,[Kettlebells (2)],rec9x7ZWD4sRRvqe3,2022-07-18 23:35:30+00:00
row_00003,2022-07-18,Battle ropes - unilateral waves,16,1800,0,3,12,NaN,Not much at ease with posture yet\n,[Battle ropes (2)],recBIG2Ixng4OkPJ4,2022-07-18 23:05:14+00:00
row_00004,2022-07-18,Battle ropes - snake waves,18,1800,0,3,12,NaN,Not much at ease with posture yet\n,[Battle ropes (2)],recGFQzOuIVmKPHx0,2022-07-18 23:05:41+00:00
row_00005,2022-07-18,Battle ropes - bilateral waves,15,1800,0,3,12,NaN,Not much at ease with posture yet\n,[Battle ropes (2)],recHiXN8REbLSpJxC,2022-07-18 23:05:20+00:00
row_00006,2022-07-18,3K,20,0,13:00,1,1,0.0,5 minutes at 15km/h (almost fell off the tread...,[None],recJxgYQPmZsBTzMQ,2022-07-18 23:05:23+00:00
row_00007,2022-07-18,Roman chair knee raise,13,7200,0,1,12,5.0,Biset with deadhang pull up\nNot touching ches...,[Dumbbell (1)],recK8Xj1Tjn1qHDAy,2022-07-18 22:54:58+00:00
row_00008,2022-07-18,Leg curl,6,2700,0,3,12,40.0,Biset with lateral raise\n,[Machine],recKZwSAkc22Xxu3E,2022-07-18 22:12:45+00:00
row_00009,2022-07-18,Leg extension,8,2700,0,3,12,40.0,Biset with upright rows\n\n,[Machine],recLKcQc1RaXwGNaR,2022-07-18 22:22:06+00:00
row_00010,2022-07-18,Deadhang pull up,12,7200,0,1,4,0.0,Biset with roman chair knee raises\nWatched fo...,[None],recPSrWRTzr7pxezH,2022-07-18 22:54:03+00:00
row_00011,2022-07-18,Battle ropes - slamming waves,17,1800,0,3,12,NaN,Not much at ease with posture yet\n,[Battle ropes (2)],recRdk1INdp8bK48R,2022-07-18 23:05:30+00:00
row_00012,2022-07-18,Battle ropes - inside waves,19,1800,0,1,1,NaN,Not much at ease with posture yet\n,[Battle ropes (2)],recSmcDgPEGwKyoXa,2022-07-18 23:05:27+00:00
row_00013,2022-07-18,Squats,4,2700,0,3,12,15.0,Biset with front raise\n,[Sandbag],recT6EMP7OgM9sLV5,2022-07-18 21:54:36+00:00
row_00014,2022-07-18,Roman chair knee raise,11,7200,0,2,12,5.0,Biset with deadhang pull up\nNot touching ches...,[Dumbbell (1)],recTmsCeMd0cEEYCQ,2022-07-18 22:44:56+00:00
row_00015,2022-07-18,Deadhang pull up,14,7200,0,1,3,0.0,Biset with roman chair knee raises\nWatched fo...,[None],recgVPkhFsoS0Fm8p,2022-07-18 22:55:06+00:00
row_00016,2022-07-18,Arnold press,9,2700,0,3,12,7.5,\n,[Dumbbells (2)],recj0VZfQdixjL6Ft,2022-07-18 22:30:07+00:00
row_00017,2022-07-18,Deadhang pull up,10,7200,0,2,3,0.0,Biset with roman chair knee raises\nWatched fo...,[None],recpSWME9CNFBw6vh,2022-07-18 22:40:22+00:00

In [112]:
df_exercises = get_df_from_airtable("EXERCISES")
df_exercises.head()

,Tool,Group,Exercise,Duration,Last executed,Objective - 12 reps (kg),Current weight -12 reps (kg),Milifranz,id,created_at,Video
row_00000,None,[Back],Deadhang pull up,0,"[recpSWME9CNFBw6vh, recPSrWRTzr7pxezH, recgVPk...",0,"[0, 0, 0]",0,recG3D1iWER7HYCI1,2022-07-18 22:40:28+00:00,NaN
row_00001,Kettlebells (2),[Shoulders],Lateral raise,0,[rec8gGo2vSU8elGpn],0,[6],{'specialValue': 'Infinity'},recME1acBxM1b6AV4,2022-07-18 22:23:37+00:00,NaN
row_00002,Battle ropes (2),[Cardio],Battle ropes - snake waves,1800,[recGFQzOuIVmKPHx0],0,NaN,{'specialValue': 'NaN'},recPefwnEXqv1SHtY,2022-07-18 23:02:11+00:00,NaN
row_00003,Dumbbells (2),[Shoulders],Arnold press,0,[recj0VZfQdixjL6Ft],0,[7.5],{'specialValue': 'Infinity'},recQdtCK6WKDORiIK,2022-07-18 22:33:03+00:00,NaN
row_00004,Sandbag,[Shoulders],Front raise,0,[rec8PfbGuChgCHBy4],0,[15],{'specialValue': 'Infinity'},recSI1YSnPbapYxxU,2022-07-18 22:23:44+00:00,NaN